### ISSUE TITLE
Fn Ctrl switch

### ISSUE THREAD

**Issue by akostadinov** [lentinj/tp-compact-keyboard#19]
Is it possible to swap Fn and Ctrl keys like in laptop BIOS?

**Comment by lentinj** [comment]
No, in short. See #18

**Comment by akostadinov** [comment]
FYI I started a thread:
http://forums.lenovo.com/t5/Displays-Options-and-Accessories/Fn-and-Ctrl-Key-swap-on-BT-keyboard/td-p/2027812

**Comment by lolmaus** [comment]
Don't expect any results from there. :(

**Comment by lolmaus** [comment]
Don't expect any results from there. :(
