### ISSUE TITLE
Use F-keys by default

### ISSUE THREAD

**Issue by akostadinov** [lentinj/tp-compact-keyboard#20]
Is it possible F keys to work as F-keys by default?

**Comment by lentinj** [comment]
What do you mean? F4/mic-mute should be F4 when you press it on it's own? That's the point of both the script and the kernel patches. It should be the default with 3.17 onwards.

**Comment by akostadinov** [comment]
Ok, excuse me, I'm considering to buy such a keyboard and I couldn't test that.

**Comment by lentinj** [comment]
No worries. FWIW the Bluetooth keyboard defaults to the function (e.g. Mic Mute), the USB defaults to the Fn key (e.g. F4). Under Linux I've added enough support that for both the default would be the Fn key, so it's irrelevant.
