### ISSUE TITLE
Swap Fn-Ctrl

### ISSUE THREAD

**Issue by eodus** [lentinj/tp-compact-keyboard#27]
Is it somehow possible to swap Fn key with left Ctrl (like on original ThinkPad keyboard)? Maybe some internal command exists or something like this?

Such feature is very desirable (not only by me, e.g. see https://forums.lenovo.com/t5/Displays-Options-and-Accessories/How-to-swap-the-Fn-and-Ctrl-key-on-ThinkPad-Compact-USB-Keyboard/td-p/1473020)

**Comment by lentinj** [comment]
#19 #18
