### ISSUE TITLE
Fn/control swap?

### ISSUE THREAD

**Issue by wkearney99** [lentinj/tp-compact-keyboard#34]
Is there a way to use this to handle swapping the FN and the Crtl keys?

I have the KU-1255 (FRU: 03X8715) USB wired Thinkpad Compact Keyboard with Trackpoint.

I'd love to be able to swap the FN & Ctrl keys as they're both on the lower left corner and I prefer Ctrl on the outside.  xev doesn't report anything when Fn alone is pressed.  It's only when used as as modifier that it appears.

Fortunately it does, at least, default to F1-F12 keys, so I don't have to worry about the Fn-Lock problem.  

Any suggestions?

**Comment by lentinj** [comment]
Not really, I don't have that keyboard. But if you can't swap them under Windows, there's probably no mechanism for swapping them.
