### ISSUE TITLE
automatically enable fn_lock

### ISSUE THREAD

**Issue by sonnyp** [lentinj/tp-compact-keyboard#46]
I have the following udev rule:

/etc/udev/rules.d/10-thinkpad-usb-keyboard.rules 
```
SUBSYSTEM=="hid", ATTRS{idVendor}=="17ef", ATTRS{idProduct}=="6047", RUN+="/opt/thinkpad-usb-keyboard-hotkeys"
```
and script:

```sh
#!/bin/sh
FILENAMES=(/sys/bus/hid/devices/*:17EF:6047*/fn_lock)

for FILENAME in ${FILENAMES}
do
  echo 0 > ${FILENAME}
done
```

It works well, but is there a better way?

**Comment by lentinj** [comment]
Not really. You could probably simplify this by using udev variable substitutions to find the path, something like ``RUN += "/bin/sh -c 'echo 0 > $devpath/fn_lock'"``, but it's not a dramatic difference.

**Comment by amosbird** [comment]
Hmm, but I cannot see any fn_lock files on arch

```
 ❯ ls /sys/bus/hid/devices/*
'/sys/bus/hid/devices/0003:17EF:306F.001F':
country  driver  hidraw  input  modalias  power  report_descriptor  subsystem  uevent

'/sys/bus/hid/devices/0003:17EF:3077.001E':
country  driver  hidraw  modalias  power  report_descriptor  subsystem  uevent

'/sys/bus/hid/devices/0003:17EF:60B5.002C':
country  driver  hidraw  input  modalias  power  report_descriptor  subsystem  uevent

'/sys/bus/hid/devices/0003:17EF:60B5.002D':
country  driver  hidraw  input  modalias  power  report_descriptor  subsystem  uevent

'/sys/bus/hid/devices/0003:17EF:60B5.002E':
country  driver  hidraw  input  modalias  power  quirks  report_descriptor  subsystem  uevent

```

**Comment by sonnyp** [comment]
@amosbird you don't see to have any Thinkpad Compact keyboard

```sh
ls /sys/bus/hid/devices/*:17EF:6047*/
```

**Comment by amosbird** [comment]
I don't. But I'm refering to this

> Linux kernels 3.17 and above (or any kernel with the kernel-patches applied) have built in support for the keyboards. This means all keys should work out the box, and you can control whether fn_lock is enabled by:

**Comment by sonnyp** [comment]
it's referring to Thinkpad Compact keyboards

**Comment by amosbird** [comment]
Ah, I see. But it's still a thinkpad keyboard, hacked from x1 tablet 3.

![image](https://user-images.githubusercontent.com/5085485/66969078-a6879f00-f0ba-11e9-958a-b6b5ad65cf90.png)

**Comment by amosbird** [comment]
I'm trying to base on the hid-lenovo.c and add fn_lock support for x1-tab3. Is there any way of finding the hid events for that keyboard's fn_lock functionality?

**Comment by lentinj** [comment]
The patches / utilities in here are for the compact keyboards, and will not support anything else. The ``fn_lock`` files are compact keyboard specific, and not how most Thinkpad keyboards work, where the Fn key is managed by the Embedded Controller.

> I'm trying to base on the hid-lenovo.c and add fn_lock support for x1-tab3

https://github.com/lentinj/tp-compact-keyboard#how-i-did-it

Regardless, this is definitely off-topic for this issue.
