### ISSUE TITLE
Switch between USB and Bluetooth?

### ISSUE THREAD

**Issue by richard-gravy** [lentinj/tp-compact-keyboard#50]
Hello,
I doubt that this is practical as they more than likely use different controllers, but as I did spend tons on my Bluetooth KT-1255 a couple of years ago, I was wondering if it can be persuaded to work as HID over USB?
Works fine, just would like the option as opposed to spending 80% again on the USB version.

**Comment by lentinj** [comment]
Correct, the SoCs on the two keyboards are entirely different. From memory the CPUs aren't even the same architecture. And regardless, according to the comments on this page the USB data lines aren't connected on the Bluetooth version: http://bdm.cc/2016/06/lenovo-bluetooth-keyboard-repairs/

So no, as nice as it would be, the Bluetooth keyboard isn't going to speak USB without major work.

In theory you can get USB Bluetooth dongles that emulate USB keyboards until they're switched to full-fat BT mode (i.e. when the operating system is ready, see https://www.0xf8.org/2014/02/the-crux-of-finding-a-hid-proxy-capable-usb-bluetooth-adapter/). I tried finding one some years ago and gave up.
