### ISSUE TITLE
Enable the "Use for Scrolling" only function on Trackpoint Keyboard(s) on MMB

### ISSUE THREAD

**Issue by thanhtacles** [lentinj/tp-compact-keyboard#55]
Traditionally on thinkpads, you can do "thinkpad scrolling" where holding the middle mouse making the mouse look like [this](https://forums.lenovo.com/t5/Displays-Options-and-Accessories/Thinkpad-Compact-USB-Keyboard-with-Trackpoint-cursor-gets-stuck-in-scrolling-mode/m-p/4102571) enables a very smooth continuous scrolling, but with the trackpoint keyboards, it's inconsistently toggling the "[panning](https://www.howtogeek.com/wp-content/uploads/2008/03/image136.png.pagespeed.ce.akPlNak2uu.png)" scroll toggle that almost nobody uses, and will sometimes even middle click. The former is what the thinkpad laptops are typically configured with and you can switch it in the setting pannel
![image](https://user-images.githubusercontent.com/64636310/122147166-33917700-ce0d-11eb-9808-a0346c6c25da.png) on their native keyboards. 

With the Trackpoint USB KBs, you don't have this. Is there a way to get this preferred trackpoint scrolling behavior on the Trackpoint Keyboard peripherals?

**Comment by lentinj** [comment]
You should ask in the Lenovo forums with help with the official driver.

These keyboards (try to) implement middle-button scrolling internally, unlike every other trackpoint setup where the middle button scrolling is managed by the drivers. My guess would be that there are several Lenovo utilities installed for managing the middle button (e.g. for your laptop's internal keyboard and your external one), and they're conflicting with each other. What you'd do about that though, I've no idea.
